### ISSUE TITLE
define commands and arguments

### ISSUE THREAD

**Issue by briceburg** [dockerland/dockmaster#3]
In #1 we suggest adding a `dm` command for interacting with compositions via a dockmaster.yml configuration file, and a `dmc` command for managing configuration. 

This issue is a placeholder -- once #1 and #2 reach consensus I'll submit a proposal.

**Comment by briceburg** [comment]
It would be nice to provide universal shortcuts via the configuration file. Somethinbg like

`dm snapshots.lan ssh cron-service`  as a shortcut to `dm snapshots.lan exec cron-service sh`

**Comment by briceburg** [comment]
@SamTay can we close this out with a documentation commit?

**Comment by samtay** [comment]
Will do
