### ISSUE TITLE
provide release script and portable binaries

### ISSUE THREAD

**Issue by briceburg** [dockerland/dockmaster#6]
we need to work out a release process/script + make potable binaries available. MacOS, Linux glibc, and Linux musl must be supported.

**Comment by samtay** [comment]
@briceburg is this good to go with latest makefile ?

**Comment by briceburg** [comment]
I haven't tested this yet, lets leave open for now. The updated  makefile didn't change compilation process.

**Comment by briceburg** [comment]
closed via f37b69a7c9c2094d5d85d6004ac363b26662c106

although the next step will be to optimize the built binaries if possible; the 12mb size is a little large for a simple app.
